package pojo;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book
 */
public class Book {
	
	private List<Chapter> chapterList;
	
	public List<Chapter> getChapterList() {
		return chapterList;
	}

	public void setChapterList(List<Chapter> chapterList) {
		this.chapterList = chapterList;
	}

	private List<Type> typeList;

	public List<Type> getTypeList() {
		return typeList;
	}

	public void setTypeList(List<Type> typeList) {
		this.typeList = typeList;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.book_id
	 * @mbg.generated
	 */
	private Integer bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.book_name
	 * @mbg.generated
	 */
	private String bookName;
	/**
	 * Database Column Remarks: 0����ͣ�� 1�����ڸ��� This field was generated by MyBatis Generator. This field corresponds to the database column book.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.create_by
	 * @mbg.generated
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.create_time
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.book_id
	 * @return  the value of book.book_id
	 * @mbg.generated
	 */
	public Integer getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.book_id
	 * @param bookId  the value for book.book_id
	 * @mbg.generated
	 */
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.book_name
	 * @return  the value of book.book_name
	 * @mbg.generated
	 */
	public String getBookName() {
		return bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.book_name
	 * @param bookName  the value for book.book_name
	 * @mbg.generated
	 */
	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.status
	 * @return  the value of book.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.status
	 * @param status  the value for book.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.create_by
	 * @return  the value of book.create_by
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.create_by
	 * @param createBy  the value for book.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.create_time
	 * @return  the value of book.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.create_time
	 * @param createTime  the value for book.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}