package pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table chapter
 */
public class Chapter {
	
	private Integer bookId;

	public Integer getBookId() {
		return bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chapter.chapter_id
	 * @mbg.generated
	 */
	private Integer chapterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chapter.chapter_title
	 * @mbg.generated
	 */
	private String chapterTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column chapter.chapter_content
	 * @mbg.generated
	 */
	private String chapterContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chapter.chapter_id
	 * @return  the value of chapter.chapter_id
	 * @mbg.generated
	 */
	public Integer getChapterId() {
		return chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chapter.chapter_id
	 * @param chapterId  the value for chapter.chapter_id
	 * @mbg.generated
	 */
	public void setChapterId(Integer chapterId) {
		this.chapterId = chapterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chapter.chapter_title
	 * @return  the value of chapter.chapter_title
	 * @mbg.generated
	 */
	public String getChapterTitle() {
		return chapterTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chapter.chapter_title
	 * @param chapterTitle  the value for chapter.chapter_title
	 * @mbg.generated
	 */
	public void setChapterTitle(String chapterTitle) {
		this.chapterTitle = chapterTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column chapter.chapter_content
	 * @return  the value of chapter.chapter_content
	 * @mbg.generated
	 */
	public String getChapterContent() {
		return chapterContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column chapter.chapter_content
	 * @param chapterContent  the value for chapter.chapter_content
	 * @mbg.generated
	 */
	public void setChapterContent(String chapterContent) {
		this.chapterContent = chapterContent;
	}
}