package pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table type
 */
public class Type {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column type.type_id
	 * @mbg.generated
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column type.type_name
	 * @mbg.generated
	 */
	private String typeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column type.type_id
	 * @return  the value of type.type_id
	 * @mbg.generated
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column type.type_id
	 * @param typeId  the value for type.type_id
	 * @mbg.generated
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column type.type_name
	 * @return  the value of type.type_name
	 * @mbg.generated
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column type.type_name
	 * @param typeName  the value for type.type_name
	 * @mbg.generated
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
}