package pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_book
 */
public class UserBook {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_book.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_book.book_id
	 * @mbg.generated
	 */
	private Integer bookId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_book.user_id
	 * @return  the value of user_book.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_book.user_id
	 * @param userId  the value for user_book.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_book.book_id
	 * @return  the value of user_book.book_id
	 * @mbg.generated
	 */
	public Integer getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_book.book_id
	 * @param bookId  the value for user_book.book_id
	 * @mbg.generated
	 */
	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}
}