package mapper;

import java.util.List;
import pojo.Book;

public interface BookMapper {
	
	Book selectBookAndType(int bookId);
	Book selectBookAndChapter(int bookId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer bookId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbg.generated
	 */
	int insert(Book row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbg.generated
	 */
	Book selectByPrimaryKey(Integer bookId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbg.generated
	 */
	List<Book> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Book row);
}