package mapper;

import java.util.List;
import pojo.Chapter;

public interface ChapterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chapter
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer chapterId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chapter
	 * @mbg.generated
	 */
	int insert(Chapter row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chapter
	 * @mbg.generated
	 */
	Chapter selectByPrimaryKey(Integer chapterId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chapter
	 * @mbg.generated
	 */
	List<Chapter> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table chapter
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Chapter row);
}