package mapper;

import java.util.List;
import pojo.Type;

public interface TypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type
	 * @mbg.generated
	 */
	int insert(Type row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type
	 * @mbg.generated
	 */
	Type selectByPrimaryKey(Integer typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type
	 * @mbg.generated
	 */
	List<Type> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Type row);
}